---

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - default.yml

- include_tasks: install.yml

- include_tasks: configure.yml
