---

system_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

system_python_packages:
  - python
  - python-pip

old_docker_packages:
  - docker
  - docker-engine
  - docker-io
  - containerd
  - runc

docker_repo: "deb [arch=amd64] https://download.docker.com/\
  {{ ansible_system | lower }}/\
  {{ ansible_distribution | lower }} \
  {{ ansible_distribution_release | lower }} \
  stable"

docker_gpg_key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
