---

# Docker package for specified version
# latest ? docker-ce
# specific ? docker-ce=18.09*
docker_package: >-
  docker-ce{{ (docker_version == 'latest') | ternary('', '=' + docker_version + '*') }}

docker_gpg_key_url: "https://download.docker.com/\
  {{ ansible_system | lower }}/\
  {{ ansible_distribution | lower}}/\
  gpg"
